name: reading_league
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  syncfusion_flutter_pdfviewer: ^23.1.36
  syncfusion_flutter_pdf: ^23.1.38
  get: ^4.6.6
  audioplayers: ^5.2.0
  path: ^1.8.0
  path_provider: ^2.0.1
  record: ^5.0.0-beta.3+1
  file_picker: ^5.5.0
  drift: ^2.12.1
  logger: ^2.0.2+1
  flutter_markdown: ^0.6.18
  markdown: ^7.1.1
  pdf: ^3.10.4
  python_ffi: ^0.4.4
  pdfx: ^2.4.0
  image: ^4.1.3
  screenshot: ^2.1.0
  font_awesome_flutter: ^10.6.0
  window_manager: ^0.3.7


  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  drift_dev: ^2.12.1


  


flutter:
  uses-material-design: true
  assets:
    - assets/documents/艺术的法则英文版.pdf
    - python-modules/split_pdf.py

python_ffi:
  modules:
    pdf_split:
      path: python-modules/split_pdf.py
    

